# Config Version [2.0]

settings:
  checkUpdate: true

database:
  hostName: "YOUR HOSTNAME"
  port: 3306
  userName: "YOUR USERNAME"
  password: "YOUR PASSWORD"

depends:
  ASkyBlock:
    interval: 10 #minute
    table: "IslandLeaderboard_ASkyBlock"
    idColumn: "id"
    leaderNameColumn: "leader"
    teamColumn: "team"
    levelColumn: "level"
    database: "YOUR DATABASE"
  IridiumSkyblock:
    interval: 10 #minute
    table: "IslandLeaderboard_IridiumSkyblock"
    idColumn: "id"
    leaderNameColumn: "leader"
    teamColumn: "team"
    levelColumn: "level"
    database: "YOUR DATABASE"
  FabledSkyBlock:
    interval: 10 #minute
    table: "IslandLeaderboard_FabledSkyBlock"
    idColumn: "id"
    leaderNameColumn: "leader"
    teamColumn: "team"
    levelColumn: "level"
    database: "YOUR DATABASE"