  name: IslandLeaderboard
  main: com.ardagunsuren.IslandLeaderboard.IslandLeaderboard
  version: "2.0"
  author: ArdaGnsrn
  website: https://ardagunsuren.com
  softdepend:
    - ASkyBlock
    - IridiumSkyblock
    - FabledSkyBlock
  commands:
      islandleaderboard:
          aliases: [isboard, ib]