  name: IslandLeaderboard
  main: com.ardagunsuren.IslandLeaderboard.IslandLeaderboard
  version: "1.1"
  author: ArdaGnsrn
  website: https://ardagunsuren.com
  softdepend:
    - ASkyBlock
    - IridiumSkyblock
  commands:
      islandleaderboard:
          aliases: [isboard, ib]